apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pictari-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pictari-api
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80