@endpoint = http://localhost:3000/account
@endpointVerif = http://localhost:3000/verification
@endpointLogin = http://localhost:3000/login

//TODO: replace hardcoded UUIDs, verification links, etc. with parameters. These are randomly generated so they won't be the same if account creation gets run on a blank database.
POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "email":"darkarts420@gmail.com",
  "name": "LordVoldemort",
  "password": "passwordlicious"
}
###
// login for above account
POST {{endpointLogin}} HTTP/1.1
content-type: application/json

{ "email":"darkarts420@gmail.com",
  "password": "passwordlicious"
}
###

POST {{endpoint}} HTTP/1.1
content-type: application/json

{ "email":"iwanttomakefriends@gmail.com",
  "name": "StopBlockingMe",
  "password": "passwordlicious"
}
###

GET {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2 HTTP/1.1
content-type: application/json

###

GET {{endpoint}}/search/Vold HTTP/1.1
content-type: application/json

###

GET {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2/profile HTTP/1.1
content-type: application/json

###

GET {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2/profile/settings HTTP/1.1
content-type: application/json

###

GET {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2/friends HTTP/1.1
content-type: application/json

###

GET {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2/friends/pending HTTP/1.1
content-type: application/json

###
GET {{endpoint}}/284a38b6-b7d9-4ad6-a2b3-c9d6d18a583a/friends/pending HTTP/1.1
content-type: application/json

###


GET {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2/blocks HTTP/1.1
content-type: application/json

###

POST {{endpoint}}/284a38b6-b7d9-4ad6-a2b3-c9d6d18a583a/friends/1366bb6d-c91d-4e5e-9836-8a101d196cf2 HTTP/1.1
content-type: application/json

###

POST {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2/friends/284a38b6-b7d9-4ad6-a2b3-c9d6d18a583a/pending HTTP/1.1
content-type: application/json

###

POST {{endpoint}}/284a38b6-b7d9-4ad6-a2b3-c9d6d18a583a/friends/1366bb6d-c91d-4e5e-9836-8a101d196cf2/pending HTTP/1.1
content-type: application/json

###

POST {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2/blocks/284a38b6-b7d9-4ad6-a2b3-c9d6d18a583a/ HTTP/1.1
content-type: application/json

###

PUT {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2/profile/settings HTTP/1.1
content-type: application/json

{
    "email":"ImVerySadNow@fakedomain.com",
    "about":"My about will never get changed..."
}

###

PUT {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2/profile/settings HTTP/1.1
content-type: application/json

{
    "about":"My about will get changed now."
}

###

DELETE {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2/blocks/284a38b6-b7d9-4ad6-a2b3-c9d6d18a583a/ HTTP/1.1
content-type: application/json

###

DELETE {{endpoint}}/1366bb6d-c91d-4e5e-9836-8a101d196cf2/friends/284a38b6-b7d9-4ad6-a2b3-c9d6d18a583a/pending HTTP/1.1
content-type: application/json

###
GET {{endpointVerif}}/LPfpNseAZ8x8h-TGodwzxgOrxWSlDUXE HTTP/1.1
content-type: application/json

###
GET {{endpointVerif}}/_NsqXJQo2M1nUdNJZ9mB_ld37_l5VvNH HTTP/1.1
content-type: application/json

###